### ISSUE TITLE
Weekly meeting

### ISSUE THREAD

**Issue by PEMapModder** [BlockServerProject/BlockServer#120]
We plan to meet on IRC `#blockserverproject` every Sunday at UTC time around 3:00 to 7:00 a.m. (we won't met all those hours, just around that time)

This issue is here for reference on what had been discussed and what will be discussed. Everyone can join and talk, but main developers are strongly encouraged to attend. This is to increase and improve communication, reflect on each other's progress and avoid incidents like the last rewrite.

### 30/11/2014
* Discuss the initiatives and progress of the rewrite
* Discussion on the current structure and its advantages and disadvantages

### 7/12/2014
(Plans)
* Is the current system sustainable?
* How, when and who will write the plugin API? (ref: #118)
* Resolve conflicts on the style and efficiency of our current structure
* What will be done in the following week

**Comment by jython234** [comment]
@BlockServerProject/developers I want everyone on this Saturday (10-12 CST(UTC -6)). We need to pull this project back together.

**Comment by PEMapModder** [comment]
Please convert to UTC.

**Comment by optrusty** [comment]
Time converted http://bit.ly/1F2rqYx

**Comment by PEMapModder** [comment]
Wt* it is sleeping time for me, I'm not available.

**Comment by jython234** [comment]
@PEMapModder  It is actually 22-24 in 24 hour time. UTC-6. You must of thought it was AM.

**Comment by PEMapModder** [comment]
@optrusty's link, blame him :P

**Comment by jython234** [comment]
@PEMapModder Acutally 4-6 AM in UTC :)

**Comment by optrusty** [comment]
@PEMapModder I am not Father Time

**Comment by jython234** [comment]
My timezone is GMT -6, just to let everyone know. We need to try to meet more often.
