### ISSUE TITLE
Encapsulation Packet Decoding problems

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#121]
Hello everyone,

Today I pulled BlockServer, and decided to run it to see what our status was. After fixing a few bugs, I found out that the encapsulation code's reading of the packet's length was wrong. The value turned out to be negative, which threw an exception when trying to initialize the array. Why this happens I am not sure, because this has never happened before, and the reading code is correct. This is however, not a mojang issue because pocketmine must of had stopped working too.

If anyone has any information relating to this, that would be great.

Thanks.

**Comment by DefinitlyEvil** [comment]
@jython234 Do NOT use the info at wiki.vg, you have to look into pocketmine's code. 0x00, 0x40 and 0x60 are not true. And sequence number and message index are not the same layer of the protocol, they have their own meaning and use.

**Comment by jython234** [comment]
@DefinitlyEvil I would like an explanation on the encapsulation format,
also if you would like, I would like to create a new, updated protocol docs
page on wiki.vg.
On Wednesday, December 31, 2014, The Evil Man <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> Do NOT use the info at wiki.vg,
> you have to look into pocketmine's code. 0x00, 0x40 and 0x60 are not true.
> And sequence number and message index are not the same layer of the
> protocol, they have their own meaning and use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/121#issuecomment-68479565>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 We can make docs by reading into pocketmine raklib's code. I think we should update wiki.vg but how can we edit it?

**Comment by Falkirks** [comment]
It's MediaWiki, just hit the edit button, you may want to make an account though.

**Comment by DefinitlyEvil** [comment]
@Falkirks :O No need to be validated by admin?

**Comment by PEMapModder** [comment]
@DefinitlyEvil do you know what is a wiki?

**Comment by DefinitlyEvil** [comment]
@PEMapModder Yea, I know what a wiki is, but I just don't know the whole editing process. xD If anyone can edit, some bad people can put useless things in it.

**Comment by jython234** [comment]
@DefinitlyEvil I have had an account for quite some time, besides, who
would want to mess up a protocol wiki? Not many people know about too.

On Thursday, January 1, 2015, The Evil Man <notifications@github.com> wrote:

> @PEMapModder <https://github.com/PEMapModder> Yea, I know what a wiki is,
> but I just don't know the whole editing process. xD If anyone can edit,
> some bad people can put useless things in it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/121#issuecomment-68482721>
> .
>


--

**Comment by jython234** [comment]
@DefinitlyEvil What timezone are you? Try to get on IRC as much as you can when free, you may be able to catch one of us.

**Comment by DefinitlyEvil** [comment]
@jython234 Okay, I will.

**Comment by jython234** [comment]
@DefinitlyEvil as soon as you read this, try to get on irc. I will try to
stay on for a little bit.

On Thursday, January 1, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Okay, I will.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/121#issuecomment-68507606>
> .
>


--
