### ISSUE TITLE
Splitted Encapsulated Packet Encoding Problem

### ISSUE THREAD

**Issue by DefinitlyEvil** [BlockServerProject/BlockServer#123]
in the file:
`/src/main/java/org/blockserver/net/protocol/pe/raknet/RaknetSentCustomPacket.java`

You forgot to write the `hasSplit` bit.

**Comment by jython234** [comment]
@DefinitlyEvil I have a few questions on FullChunkDataPackets. I have looked at your code, and mine seems to be all in order (I have all fields, compressed, little endian etc..). However, my client still does not seem to accept my chunks. Using wireshark I discovered that you seem to split your packets into sizes around 1000 - 1400. However, when sending mine whole, they turn out to be in that range, unsplit. I then copied your encapsulation code, and suddenly everything was a mess. Some packets where splitting when not needing, wireshark thought some where IPV4 packets. I was wondering if you could look at my project, I can never seem to get past sending chunks... I will upload it soon.

**Comment by jython234** [comment]
@DefinitlyEvil https://github.com/jython234/MCBridge

**Comment by PEMapModder** [comment]
@jython234 MTU

**Comment by DefinitlyEvil** [comment]
@jython234 Yep, the client sends it's MTU when connecting. You should check each packet wether bigger than MTU, if yes, split it and use a new split ID. I hope my words can help you.

**Comment by jython234** [comment]
I understand, that's what I am doing. Did you look at my code?

On Friday, January 2, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Yep, the client sends it's MTU
> when connecting. You should check each packet wether bigger than MTU, if
> yes, split it and use a new split ID. I hope my words can help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/123#issuecomment-68584398>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 See you on the IRC.

**Comment by DefinitlyEvil** [comment]
@jython234 You were not on the IRC, but I found some possible problems you may want to resolve. And let's discuss in your repo's issue, it's not about BlockServer. xD

**Comment by jython234** [comment]
@DefinitlyEvil I think I left a couple minutes before you joined xD.

**Comment by PEMapModder** [comment]
Is this fixed? If yes, close it.

**Comment by jython234** [comment]
@PEMapModder Not sure, I'll let @DefinitlyEvil close this.

**Comment by DefinitlyEvil** [comment]
Okay. :)
