### ISSUE TITLE
Structure of Play Packets

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#126]
I have gotten a little confused over how to implement play packets after ClientHandshake. Or are play packets after FullChunkDataPacket(0xba)? I am not sure. Also, how does the Subprotocol, and the generic, and PeDataPacket all fit in?

**Comment by PEMapModder** [comment]
When the client sends a packet about its protocol, the server should determine a compatible subprotocol (MCPE protocol version adapter) class for that protocol and instantiate a new object of that version, or disconnect the client for incompatible version on failure.
Assuming these all get implemented, this is how the server would handle:

```
Bridges: UDP and TCP
↓ calls when packet received
ProtocolManager
↓ manages and passes packets to
Protocols: PeProtocol (and maybe McpcProtocol if support MCPC)
↓ handles the initial handshake packets and chooses
Subprotocols: compatible for different versions of the Protocol (e.g. different versions of MCPE)

**Comment by jython234** [comment]
I was a little unclear on how to implement play packets (for example
Ping/Pong). Should I extend PeDatPacket?

On Friday, January 9, 2015, PEMapModder <notifications@github.com> wrote:

> When the client sends a packet about its protocol, the server should
> determine a compatible subprotocol (MCPE protocol version adapter) class
> for that protocol and instantiate a new object of that version, or
> disconnect the client for incompatible version on failure.
> Assuming these all get implemented, this is how the server would handle:
>
> Bridges: UDP and TCP
> ↓ calls when packet received
> ProtocolManager
> ↓ manages and passes packets to
> Protocols: PeProtocol (and maybe McpcProtocol if support MCPC)
> ↓ handles the initial handshake packets and chooses
> Subprotocols: compatible for different versions of the Protocol (e.g. different versions of MCPE)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/126#issuecomment-69438825>
> .
>


--

**Comment by jython234** [comment]
@PEMapModder And also what package should I put these packets in, and how to use them?

**Comment by jython234** [comment]
@PEMapModder There is a problem with the Subprotocols. How is the subprotocol supposed to send the response? The way it is structured makes it difficult, and I don't want to mess up your code. Please respond, I need an answer.

**Comment by PEMapModder** [comment]
@jython234 can IRC?

**Comment by PEMapModder** [comment]
Life cycle of a request and a response
```
MCPE client
↓ (bytes)
Internet
↓  (bytes)
NetworkBridge
↓ (WrappedPacket)
ProtocolManager
↓ (WrappedPacket)
Subprotocol
↓ (WrappedPacket)
SubprotocolSession
    (WrappedPacket, a ByteBuffer+NetworkBridge representation
    → translate to MCPE data packets
    → adapt into BlockServer internal "request" structures)
↓ (InternalRequest)
Player (handling)
↓ (InternalResponse)
SubprotocolSession
    → adapt into MCPE data packets
    → add into packet queue
    → send the encapsulated packet through the NetworkBridge
↓ (WrappedPacket)
NetworkBridge
↓ (bytes)
Internet
↓ (bytes)
MCPE client

**Comment by AndreyNazarchuk** [comment]
The server has to go through all of this for every packet? Or just during
original handshake?

**Comment by PEMapModder** [comment]
Do toy think we can simplify if we want to support any protocols? Actually this is not very complicated. It is just passing a variable through different objects, parse an encapsulated packet and convert and then convert an MCPE packet to an internal structure.
The above flowchart is a bit wrong. I will edit it.

**Comment by PEMapModder** [comment]
Protocol => edition of Minecraft, e.g. MCPE
Subprotocol => protocol version of a certain edition of Minecraft, e.g. MCPE protocol #20

**Comment by jython234** [comment]
Ahh totally forgot about that request/response part. I will try and
implement ping/pong today. If I have time I will send dummy chunks too.

On Friday, January 16, 2015, PEMapModder <notifications@github.com> wrote:

> Protocol => edition of Minecraft, e.g. MCPE
> Subprotocol => protocol version of a certain edition of Minecraft, e.g.
> MCPE protocol #20
> <https://github.com/BlockServerProject/BlockServer/issues/20>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/126#issuecomment-70212229>
> .
>


--

**Comment by jython234** [comment]
@PEMapModder i went to sleep at my usual time yesterday, so I could not
irc. I might be able to today, and of course I'm on after school (way in
the morning for you).

On Friday, January 16, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> Ahh totally forgot about that request/response part. I will try and
> implement ping/pong today. If I have time I will send dummy chunks too.
>
> On Friday, January 16, 2015, PEMapModder <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Protocol => edition of Minecraft, e.g. MCPE
>> Subprotocol => protocol version of a certain edition of Minecraft, e.g.
>> MCPE protocol #20
>> <https://github.com/BlockServerProject/BlockServer/issues/20>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BlockServerProject/BlockServer/issues/126#issuecomment-70212229>
>> .
>>
>
>
> --
>
>

--

**Comment by jython234** [comment]
@PEMapModder I am still not clear, this structure is a bit confusing. First of all, how does the Subprotocol class get the right player to handle the request to? And, I assume that by "subprotocolsession" you mean "PeProtocolSession". If so, then where does PeSubprotocolGen come in? Very confused.

**Comment by PEMapModder** [comment]
There is a `Map<SocketAddress, ProtocolSession>` in `ProtocolManager`. When a packet is received, it first checks if the incoming address is in the map. If true, the packet is passed into the corresponding `ProtocolSession` to be handled. Otherwise, it loops through the `Protocol`s in the manager and if a manager returns a `ProtocolSession` instance, it is inserted into the `Map`.

After a packet containing the MCPE version info is passed into the Session, it will search for a corresponding `Subprotocol`. If no subprotocol is found, it will close the connection for incompatible version. If yes, it will store a `Subprotocol` instance and later packets will be passed to it.
`Gen` is the base subprotocol that won't be used. Packets should be passed into `V20`, which extends `Gen` and adds protocol \#20-exclusive packets into it.
I think future packets would only base on \#20 and add extensions (rather than rewriting the whole protocol) however, so maybe `Gen` is not needed and future protocols could extend \#20.

**Comment by PEMapModder** [comment]
Sorry there isn't something called SubprotocolSession. Me wrong

**Comment by jython234** [comment]
@PEMapModder But for sending the response, the SubprotocolV20 class doesnt have the address where the packet came from, so it's impossible to get the Player class to handle the request.

**Comment by PEMapModder** [comment]
You should be able to get it from the ProtocolSession

**Comment by jython234** [comment]
The subprotocolV20 class doesn't have access to the specific session. And
it can't use that map because it doesn't know where the packet came from.

On Saturday, January 17, 2015, PEMapModder <notifications@github.com> wrote:

> You should be able to get it from the ProtocolSession
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/126#issuecomment-70395234>
> .
>


--

**Comment by PEMapModder** [comment]
Hmm, right. Change `void Subprotocol.handleDataPacket(PeDataPacket)` return type to `InternalRequest`.

**Comment by jython234** [comment]
@PEMapModder Got it.
