### ISSUE TITLE
Duplicated Packets?

### ISSUE THREAD

**Issue by DefinitlyEvil** [BlockServerProject/BlockServer#127]
If network lags, client can't get ACK packet, and packets are resent then server will receive duplicated packets. How do we solve this problem?

**Comment by jython234** [comment]
The client is only supposed to send missing packets when a NACK is recived,
I thought?

On Sunday, January 11, 2015, The Evil Man <notifications@github.com> wrote:

> If network lags, client can't get ACK packet, and packets are resent then
> server will receive duplicated packets. How do we solve this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127>.
>


--

**Comment by jython234** [comment]
Also, once this happened with chat packets, it kept spamming forever. I
forgot wether it was the client or servers fault.

On Sunday, January 11, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> The client is only supposed to send missing packets when a NACK is
> recived, I thought?
>
> On Sunday, January 11, 2015, The Evil Man <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> If network lags, client can't get ACK packet, and packets are resent then
>> server will receive duplicated packets. How do we solve this problem?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BlockServerProject/BlockServer/issues/127>.
>>
>
>
> --
>
>

--

**Comment by DefinitlyEvil** [comment]
Sometimes we got 2 or more but not spamming.

**Comment by DefinitlyEvil** [comment]
Get on the IRC please. :)

**Comment by jython234** [comment]
I am on.

On Sunday, January 11, 2015, The Evil Man <notifications@github.com> wrote:

> Get on the IRC please. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-69497350>
> .
>


--

**Comment by DefinitlyEvil** [comment]
XD You didn't reply to me. Antways, I studied RakNet a bit before, and client seems to resends packet if it got no ACK in few seconds. If network is bad, ACK may be dropped.

**Comment by jython234** [comment]
@DefinitlyEvil You were not on when I joined xD, I missed you by a few minutes.

**Comment by DefinitlyEvil** [comment]
Wtf! xD

**Comment by jython234** [comment]
Lol.

On Monday, January 12, 2015, The Evil Man <notifications@github.com> wrote:

> Wtf! xD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-69545644>
> .
>


--

**Comment by PEMapModder** [comment]
Please close this issue if it has been fixed.

**Comment by jython234** [comment]
@PEMapModder This has not been fixed.

**Comment by jython234** [comment]
@DefinitlyEvil @PEMapModder I don't think this issue IS fixable.

**Comment by DefinitlyEvil** [comment]
Well, Shoghi fixed this.

**Comment by jython234** [comment]
I guess you could check each packet buffer and see if it was sent a few
seconds ago.

On Monday, June 1, 2015, The Evil Man <notifications@github.com> wrote:

> Well, Shoghi fixed this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-107355922>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Don't! It will cost too much extra un-needed CPU time.

**Comment by jython234** [comment]
I know, that's why I nebver implemented that.

On Monday, June 1, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Don't! It will cost too much
> extra un-needed CPU time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-107469597>
> .
>


--

**Comment by jython234** [comment]
@DefinitlyEvil Of course! We check the sequence number against our lastSeqNum and figure out if it's a duplicate. I think I saw something like that when I was porting RakLib to Python (Took one week!)

**Comment by DefinitlyEvil** [comment]
@jython234 What of the number is the packet which was lost during transmission?

**Comment by jython234** [comment]
Nvm.

On Saturday, June 13, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> What of the number is the
> packet which was lost during transmission?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-111767516>
> .
>


--

**Comment by jython234** [comment]
Port of RakLib (JRakLib) will solve this problem: #146

**Comment by DefinitlyEvil** [comment]
@jython234 Could you please make a document for how to use it? :3

**Comment by jython234** [comment]
@DefinitlyEvil I am assuming you would like to use it for Dragonet? I created a getting started guide on the library's wiki (https://github.com/BlockServerProject/JRakLib/wiki/Getting%20Started) and you can find the javadoc here: http://blockserverproject.github.io/JRakLib/. It may be a bit vague,  so if you have any problems setting up feel free to email me at jython234@gmail.com

**Comment by DefinitlyEvil** [comment]
@jython234 Thank you so much man! :D You're awesome!

**Comment by jython234** [comment]
No problem!

On Tuesday, August 4, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Thank you so much man! :D
> You're awesome!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/127#issuecomment-127486828>
> .
>


--
