### ISSUE TITLE
API Structure

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#129]
We decided #118. Now it is time to straighten out the structure of the API. First of all, does blockserver implement an API loader? Or is PocketBukkit just a fork of BlockServer with API support? I propose we implement a simple API loader to load PocketBukkit's JAR. Then, we can pass important instances to PocketBukkit, along with events, so it can do the handling. Any other ideas?

**Comment by PEMapModder** [comment]
I suggest that PocketBukkit loads BlockServer and passes an `API` instance instead, where this `API` is an interface with methods like:

```java
public interface API{
    public boolean onPlayerJoin(Player player, Argument<String> joinMessage); // return true if not cancelled, false if cancelled
    public static class Argument<T>{
        public T value;
        public Argument(T value){
            this.value = value;
        }
}
```

Then BlockServer calls these methods, PocketBukkit will pass this to different plugins, plugins can modify the cancelled state and the arguments, then BlockServer can check the values.

===
The above is my proposal.

**Comment by PEMapModder** [comment]
@jython234 don't label everything you want as "high priority". We haven't even finished the networking part, how could this be "high priority"?

**Comment by jython234** [comment]
@PEMapModder Sorry. Do you mean that BlockServer loads PocketBukkit?

**Comment by PEMapModder** [comment]
No. I meant the starter of PocketBukkit loads BlockServer, then objects PocketBukkit into BlockServer.

**Comment by jython234** [comment]
Ahh using the server builder? Also I was wondering wether to rewrite
pocketbukkit, or leave it the way it is.

On Monday, January 26, 2015, PEMapModder <notifications@github.com> wrote:

> No. I meant the starter of PocketBukkit loads BlockServer, then objects
> PocketBukkit into BlockServer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/129#issuecomment-71434283>
> .
>


--

**Comment by AndreyNazarchuk** [comment]
Will there be a RubberBand type feature or plugin?

**Comment by jython234** [comment]
@AndreyNazarchuk https://github.com/jython234/BouncyBall.

**Comment by AndreyNazarchuk** [comment]
Yay! I like the name lol.

**Comment by AndreyNazarchuk** [comment]
Does this work yet?

**Comment by jython234** [comment]
Yes, it doesn't support multiple servers yet. I will upload some
instructions to set it up.

On Monday, March 30, 2015, Andrey Nazarchuk <notifications@github.com>
wrote:

> Does this work yet?
> On Mar 30, 2015 7:38 PM, "Andrey Nazarchuk" <andynazay153@gmail.com
> <javascript:_e(%7B%7D,'cvml','andynazay153@gmail.com');>> wrote:
>
> > Yay! I like the name lol.
> > On Mar 30, 2015 6:33 PM, "jython234" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> >> @AndreyNazarchuk <https://github.com/AndreyNazarchuk>
> >> https://github.com/jython234/BouncyBall.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/BlockServerProject/BlockServer/issues/129#issuecomment-87894884
> >
> >> .
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/129#issuecomment-87907955>
> .
>


--

**Comment by AndreyNazarchuk** [comment]
OK, thanks

**Comment by jython234** [comment]
@AndreyNazarchuk: https://github.com/jython234/BouncyBall/blob/master/README.md
