### ISSUE TITLE
Chunk Sending

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#131]
First of all, let's get this Chunk Sending problem fixed. I have no idea what is wrong, I even used the code from the old branch which did work, and it didn't work here. If anyone has information about it, please comment here.

##### Note to @PEMapModder: This is truly High Priority.

**Comment by PEMapModder** [comment]
Yes I know it is this time :D

**Comment by jython234** [comment]
:)

**Comment by jython234** [comment]
@DefinitlyEvil

On Monday, January 26, 2015, PEMapModder <notifications@github.com> wrote:

> Yes I know it is this time :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-71434356>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 
in DummyChunk class: 
```
    public void generate(){
        int offset = 0;
        for(int x = 0; x < 16; x++){
            for(int z = 0; z < 16; z++){
                blockIds[offset] = 0x02;
                for(int y = 0; y < 127; y++){
                    blockIds[offset] = 0x00;
                }
            }
            offset++;
        }

        for(int i = 0; i < 256; i++){
            biomeIds[i] = (byte) 0xFF;
        }
    }
```
The problem is you forgot to generate a layer of blocks. 
```
for(int y = 0; y < 127; y++){
```
where 127 should be 128.

**Comment by jython234** [comment]
@DefinitlyEvil I generate a block of grass before that loop, the is why it
is 127. I think there may be a flaw with our encapsulation. @PEMapModder we
need split support.

On Friday, January 30, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234>
> in DummyChunk class:
>
>     public void generate(){
>         int offset = 0;
>         for(int x = 0; x < 16; x++){
>             for(int z = 0; z < 16; z++){
>                 blockIds[offset] = 0x02;
>                 for(int y = 0; y < 127; y++){
>                     blockIds[offset] = 0x00;
>                 }
>             }
>             offset++;
>         }
>
>         for(int i = 0; i < 256; i++){
>             biomeIds[i] = (byte) 0xFF;
>         }
>     }
>
> The problem is you forgot to generate a layer of blocks.
>
> for(int y = 0; y < 127; y++){
>
> where 127 should be 128.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-72304761>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Just grab the code from Dragonet, I gave that project to TheMCPEGamer.

**Comment by jython234** [comment]
@DefinitlyEvil I tried that with mcbridge and it didn't work.

On Saturday, January 31, 2015, The Evil Man <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> Just grab the code from
> Dragonet, I gave that project to TheMCPEGamer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-72349145>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Maybe the bridge thing has some problem.

**Comment by jython234** [comment]
@DefinitlyEvil the minimum amount of chunks to be sent before spawning is
49(7x7) or 56(7x8)?

On Sunday, February 1, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Maybe the bridge thing has some
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-72372764>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Just more than 56 is good. :)

**Comment by jython234** [comment]
Alright, thought it was 49 xD.

On Monday, February 9, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Just more than 56 is good. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-73481845>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Better use 8x8.

**Comment by jython234** [comment]
@DefinitlyEvil Alright, If you can get on IRC.

**Comment by jython234** [comment]
Well, the problem is most likely our packet format... The client must not like something inside the chunk packets, because if they were fine, it would display the "building terrain" screen.

**Comment by DefinitlyEvil** [comment]
@jython234 The progress bar only grows when a valid chunk sent.

**Comment by InusualZ** [comment]
You should check this: https://github.com/NiclasOlofsson/MiNET

**Comment by jython234** [comment]
@InusualZ already did.

On Saturday, February 14, 2015, InusualZ <notifications@github.com> wrote:

> You should check this: https://github.com/NiclasOlofsson/MiNET
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-74378677>
> .
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Maybe the InternalPacket thing cuased some packet format issue.

**Comment by jython234** [comment]
I'm pretty sure not. That code looks correct. Or maybe we need to separate
the packets? Idk.

On Monday, February 16, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Maybe the InternalPacket thing
> cuased some packet format issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-74465528>
> .
>


--

**Comment by jython234** [comment]
@DefinitlyEvil Everything looks right...

**Comment by DefinitlyEvil** [comment]
@jython234 I have totally no idea now. Everythinkg looks right as you said.

**Comment by jython234** [comment]
@DefinitlyEvil maybe it's one of the packets before the chunks.

On Friday, February 20, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> I have totally no idea now.
> Everythinkg looks right as you said.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-75275365>
> .
>


--

**Comment by jython234** [comment]
Also, something strange happens: after all the chunks are sent the client
keeps sending pongs to me, and their ACK packets have the sequence number
way lower than our counter. It's like it doesn't even care about the custom
packets with chunks.

On Tuesday, February 24, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> @DefinitlyEvil maybe it's one of the packets before the chunks.
>
> On Friday, February 20, 2015, The Evil Man <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @jython234 <https://github.com/jython234> I have totally no idea now.
>> Everythinkg looks right as you said.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BlockServerProject/BlockServer/issues/131#issuecomment-75275365>
>> .
>>
>
>
> --
>
>

--
