### ISSUE TITLE
Builds Deployment

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#134]
Hey everyone,

In order for people to use BlockServer, they need to set it up. Now, for us, it's easy. But, for the average server owner, it may be hard. So, I have came up with a plan. We could create two installers (One Shell/Java for linux/mac, One in Visual C# for windows). Each would download the latest build from our build server, or compile it itself. The program would be completely automated, with no need for user input. Just double click or press enter and boom done.

I could use some input on this idea, and feel free to suggest your ideas too, everyone is welcome!

**Comment by AndreyNazarchuk** [comment]
A zip would be OK also, if that is easier.

**Comment by PEMapModder** [comment]
There is `iexpress` in Windows, see if it helps.

**Comment by PEMapModder** [comment]
Actually we can also make a jar executable, and that should not be too hard to run for the users.

**Comment by jython234** [comment]
Maven does that already, the catch is our dependency jars. Maven shade
plugin might help.

On Wednesday, February 25, 2015, PEMapModder <notifications@github.com>
wrote:

> Actually we can also make a jar executable, and that should not be too
> hard to run for the users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76083943>
> .
>


--

**Comment by jython234** [comment]
And I've used iexpress I think.

On Wednesday, February 25, 2015, PEMapModder <notifications@github.com>
wrote:

> Actually we can also make a jar executable, and that should not be too
> hard to run for the users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76083943>
> .
>


--

**Comment by jython234** [comment]
Apparently iexpress doesn't like jars xD.

On Wednesday, February 25, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> And I've used iexpress I think.
>
> On Wednesday, February 25, 2015, PEMapModder <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Actually we can also make a jar executable, and that should not be too
>> hard to run for the users.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76083943>
>> .
>>
>
>
> --
>
>

--

**Comment by PEMapModder** [comment]
We should work on BlockServer-Runner.

**Comment by jython234** [comment]
Meh.

On Thursday, February 26, 2015, PEMapModder <notifications@github.com>
wrote:

> We should work on BlockServer-Runner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76180042>
> .
>


--

**Comment by jython234** [comment]
Isn't BlockServer runner the GUI?

On Thursday, February 26, 2015, Alejandro Zeise <atzeise@gmail.com> wrote:

> Meh.
>
> On Thursday, February 26, 2015, PEMapModder <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> We should work on BlockServer-Runner.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76180042>
>> .
>>
>
>
> --
>
>

--

**Comment by PEMapModder** [comment]
I mean, make the installer for the runner, not the source. People who don't know how to install find running on console annoying too.

**Comment by AndreyNazarchuk** [comment]
Can you make a console option also, if not separate from then at least
inside the gui? Some people are used to consoles.

**Comment by jython234** [comment]
@AndreyNazarchuk This repo is the console version :)

**Comment by PEMapModder** [comment]
@AndreyNazarchuk even if we have the GUI, it's still console based

Also, @jython234 we may want to have a part of API that is about GUI.

**Comment by jython234** [comment]
As for the build server, I was thinking of using a BlockServer module for
the server.

On Friday, February 27, 2015, PEMapModder <notifications@github.com> wrote:

> @AndreyNazarchuk <https://github.com/AndreyNazarchuk> even if we have the
> GUI, it's still console based
>
> Also, @jython234 <https://github.com/jython234> we may want to have a
> part of API that is about GUI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-76420204>
> .
>


--

**Comment by optrusty** [comment]
@jython234 @PEMapModder I don't get what so important about a GUI. We know that a previous server owner has used PocketMine and pocketmine doesnt have a GUI. Unless the console is different.

**Comment by AndreyNazarchuk** [comment]
Honestly, if they can't use a console, they should ask around or just not
run a server.

**Comment by jython234** [comment]
@AndreyNazarchuk I agree xD.

**Comment by optrusty** [comment]
@jython234 IRC?

**Comment by jython234** [comment]
http://builds.blockserver.org or http://teamcity.beaconpe.net
Build Server is now set up. Please create an account there, or just check it out.

**Comment by AndreyNazarchuk** [comment]
Made an account, but what is it for? Sorry, I am a Java noob, still
learning.

**Comment by jython234** [comment]
@AndreyNazarchuk Just to be notified on builds and other things. Much to discover. You can download the latest builds from the project page.

**Comment by PEMapModder** [comment]
Actually, if they don't know how to use it, they can just make a new server software or not to use it. Why help them?

We are here to ease using our software and provide convenience. Who likes using console if there is a GUI?

The advantage of GUI is the ease to read and control. If you don't understand, just host a production PocketMine server yourself with more plugins and you'll understand.

**Comment by optrusty** [comment]
@PEMapModder But is it really necessary for a GUI right now? Getting the main project done is more important

**Comment by PEMapModder** [comment]
@optrusty no. But I would work on it when I get bores.

**Comment by optrusty** [comment]
@PEMapModder lol... I'm on IRC you want to talk about there

**Comment by jython234** [comment]
@PEMapModder, @optrusty you should check out http:/:builds.blockserver.org

On Friday, March 6, 2015, optrusty <notifications@github.com> wrote:

> @PEMapModder <https://github.com/PEMapModder> lol... I'm on IRC you want
> to talk about there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-77558165>
> .
>


--

**Comment by optrusty** [comment]
@jython234 Which file do I download BlockServer-1.0.0-BETA-SNAPSHOT.jar (127.19 KB)
BlockServer-IO-Lib-0.0-BETA-SNAPSHOT.jar (42.68 KB)
commons-lang3-3.3.2.jar (403.06 KB)
guava-16.0.1.jar (2.12 MB)
leveldb-0.8-SNAPSHOT.jar (228.85 KB)
leveldb-api-0.8-SNAPSHOT.jar (9.17 KB)
log4j-api-2.0-rc1.jar (113.48 KB)
log4j-core-2.0-rc1.jar (686.19 KB)
snakeyaml-1.14.jar (268.66 KB)

**Comment by jython234** [comment]
It's a little complicated. You need BlockServer-1.0.0-BETA-SNAPSHOT.jar in
a folder. Then create another folder called "lib" place the rest of the
jars in it. Then launch the BlockServer jar and see if it works.

On Friday, March 6, 2015, optrusty <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> Which file do I download
> BlockServer-1.0.0-BETA-SNAPSHOT.jar (127.19 KB)
> BlockServer-IO-Lib-0.0-BETA-SNAPSHOT.jar (42.68 KB)
> commons-lang3-3.3.2.jar (403.06 KB)
> guava-16.0.1.jar (2.12 MB)
> leveldb-0.8-SNAPSHOT.jar (228.85 KB)
> leveldb-api-0.8-SNAPSHOT.jar (9.17 KB)
> log4j-api-2.0-rc1.jar (113.48 KB)
> log4j-core-2.0-rc1.jar (686.19 KB)
> snakeyaml-1.14.jar (268.66 KB)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/134#issuecomment-77567448>
> .
>


--
