### ISSUE TITLE
Use PositionInteger for integral positions

### ISSUE THREAD

**Issue by PEMapModder** [BlockServerProject/BlockServer#135]
It is neither correct nor efficient to use `PositionDoublePrecision` for integral positions. In Java, `int`s should not be mixed with `double`s as they will remain in double form forever, and also possible precision issues. It is also faster to use ints directly, especially during heavy procedures like world generation and chunk handling.

**Comment by jython234** [comment]
@PEMapModder Use double precision for only player positions, and int for the rest.

**Comment by PEMapModder** [comment]
So change that for things like blocks.
