### ISSUE TITLE
Client Ignores Chunk Packets

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#136]
The Client appears to seem to ignore chunk packets. After all packets are sent, the client keeps sending it's ping/pong as usual, but with different sequence numbers! For example, the last chunk packet's sequence number is 31, but the client responds with a 0x00 PING with a sequence number of 3! However, the client does ACK the chunk packets with the correct sequence numbers, but doesn't seem to stay with us.

**Comment by jython234** [comment]
Same happens with message index.

**Comment by jython234** [comment]
I assume our encapsulation implementation is incorrect, as this problem happens in my other projects also(such as BouncyBall).

**Comment by Addison118** [comment]
Test
