### ISSUE TITLE
Some branch changes

### ISSUE THREAD

**Issue by PEMapModder** [BlockServerProject/BlockServer#137]
The `master` branch has just been renamed to `old`, and the `new` branch has been copied to `master` branch. The default branch ahs been set to `master` as well. The `new` branch shall be deleted in about one week to fully execute the branch renaming, so please update your local clones of this branch.

A possible way to adapt to the new changes:
```cmd
git branch -D master
git fetch origin
git checkout master
```

If it doesn't work, please remove the directory and clone again.

**Comment by PEMapModder** [comment]
Also, the default branch has been set to `master`.

**Comment by jython234** [comment]
Good job.

On Saturday, April 11, 2015, PEMapModder <notifications@github.com> wrote:

> Also, the default branch has been set to master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/137#issuecomment-91782646>
> .
>


--

**Comment by jython234** [comment]
I think everyone is aware of this by now.
