### ISSUE TITLE
Spawn position

### ISSUE THREAD

**Issue by PEMapModder** [BlockServerProject/BlockServer#138]
There seems to be some issues with the spawn. Is it the chunk position or the coordinates? Because the object was passed to the constructor of `Chunk` directly, which is incorrect.

**Comment by PEMapModder** [comment]
And what is the point of having a `LevelManager` if there is only one level?

**Comment by jython234** [comment]
Good question actually. I believe it is the coordinates. Also that level
manager is for when we support multiple levels, and for different types
(level db, anvil, etc).

On Saturday, April 11, 2015, PEMapModder <notifications@github.com> wrote:

> Assigned #138
> <https://github.com/BlockServerProject/BlockServer/issues/138> to
> @jython234 <https://github.com/jython234>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/138#event-278715219>
> .
>


--

**Comment by PEMapModder** [comment]
I think I fixed it.
Also, don't mix up int and doubles. That can lead to terrible results.
And make another class for ChunkPosition! (I already did) We want memory optimization.

**Comment by jython234** [comment]
got it. I was unaware that you commited recently, I'll go check it out.

On Saturday, April 11, 2015, PEMapModder <notifications@github.com> wrote:

> Closed #138 <https://github.com/BlockServerProject/BlockServer/issues/138>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/138#event-278821159>
> .
>


--
