### ISSUE TITLE
Do some work :)

### ISSUE THREAD

**Issue by EnderBrine101** [BlockServerProject/BlockServer#139]
You wonder why BlockServer is becoming dead...try commiting a bit morr and advertise the software on other websites.

**Comment by PEMapModder** [comment]
Because we the main developers don't have time, and we already advertized but nobody is concerned about a project that isn't finished.

**Comment by jython234** [comment]
BlockServer isn't dead, it's just that we are overwhelmed with school, and
other projects. I hope to get development up during the summer.

On Monday, April 20, 2015, PEMapModder <notifications@github.com> wrote:

> Closed #139 <https://github.com/BlockServerProject/BlockServer/issues/139>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/139#event-284999783>
> .
>


--

**Comment by PEMapModder** [comment]
I hope to finish all my projects that I am in charge of / being the main developer before September. I need to concentrate at school with HKDSE coming in 2017; I can't spend al my time here then, so I'll no longer be this active after this summer.

**Comment by EnderBrine101** [comment]
@PEMapModder 2 things. #1: Thats alright. School id always more important :) #2: this is not a forum!

**Comment by AndreyNazarchuk** [comment]
Then you started this issue so no one would reply?

**Comment by EnderBrine101** [comment]
I was referencing what PEMapModder was telling me about this is not a forum.

**Comment by AndreyNazarchuk** [comment]
In your own post?

**Comment by PEMapModder** [comment]
@EnderBrine101 I am commenting here to acknowledge that the schedule needs to be altered.
