### ISSUE TITLE
Project Organization

### ISSUE THREAD

**Issue by Exerosis** [BlockServerProject/BlockServer#148]
How should we organize all the parts of our server?https://github.com/BlockServerProject/BlockServer/commit/f0a76e8a64bec6b16d0255e2c5b2edfcd2142d23
~ I split it into implmention and core but its not perfect.

**Comment by PEMapModder** [comment]
Can you elaborate more?

**Comment by Exerosis** [comment]
Sure, we have our modules, events, and loaders, as well as the abstract classes and interfaces they extend. Along with that we have the actual event system and the server. I just wanted to see how you guys wanted it organized and seperated.

**Comment by PEMapModder** [comment]
I don't see that necessary for this project.

**Comment by Exerosis** [comment]
Lol, why not? Its quite a large project. If we left it a jumble nobody would dev for it x)

**Comment by jython234** [comment]
@Exerosis I think you misunderstand, there is no "implementation", the core itself is the implementation. It's up to external modules to add PE and PC support.

**Comment by Exerosis** [comment]
Well... for now maybe... eventually we need to split it up way more then it is now. So that if somebody wanted they could launch the server with nothing but TaskModule, NetworkModule, and ServerListModule.

**Comment by PEMapModder** [comment]
I know, but it looks fine right now, doesn't it?

**Comment by jython234** [comment]
I think this is settled.
